version: "3.8"

services:
        db:
                image: postgres:13-alpine
                environment: 
                        POSTGRES_PASSWORD: superstr0ngpass
                ports:
                        - "5432:5432"
                volumes: 
                        - /home/temur/data3:/var/lib/db
                          
        dbviewer:
                image: dpage/pgadmin4:latest
                environment:
                        PGADMIN_DEFAULT_EMAIL: temurpallaev@gmail.com 
                        PGADMIN_DEFAULT_PASSWORD: pss123
                ports: 
                        - "${PGADMIN_PORT:-5050}:5432"
                depends_on:
                        - db         
